import type { Metadata } from "next";
import { REM } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import fetchData from "./components/helpers/fetchData";

const rem = REM({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetchData('page/1')

  return (
    <html lang="pt-BR">
      <body className={rem.className}>
        <Header data={data.configs}/>
        {children}
        <Footer data={data.configs}/>
      </body>
    </html>
  );
}
